export type TileType = "grass" | "path" | "buildable";

export const boardData: TileType[][] = [
  [
    "buildable",
    "buildable",
    "buildable",
    "buildable",
    "buildable",
    "buildable",
    "buildable",
    "buildable",
  ],
  ["path", "path", "path", "path", "path", "path", "path", "path"],
  [
    "buildable",
    "buildable",
    "buildable",
    "buildable",
    "buildable",
    "buildable",
    "buildable",
    "path",
  ],
  ["path", "path", "path", "path", "path", "path", "path", "path"],
  [
    "path",
    "buildable",
    "buildable",
    "buildable",
    "buildable",
    "buildable",
    "buildable",
    "buildable",
  ],
  ["path", "path", "path", "path", "path", "path", "path", "path"],
];

export const PATH = [
  { row: 1, col: 0 },
  { row: 1, col: 1 },
  { row: 1, col: 2 },
  { row: 1, col: 3 },
  { row: 1, col: 4 },
  { row: 1, col: 5 },
  { row: 1, col: 6 },
  { row: 1, col: 7 },
  { row: 2, col: 7 },
  { row: 3, col: 7 },
  { row: 3, col: 6 },
  { row: 3, col: 5 },
  { row: 3, col: 4 },
  { row: 3, col: 3 },
  { row: 3, col: 2 },
  { row: 3, col: 1 },
  { row: 3, col: 0 },
  { row: 4, col: 0 },
  { row: 5, col: 0 },
  { row: 5, col: 1 },
  { row: 5, col: 2 },
  { row: 5, col: 3 },
  { row: 5, col: 4 },
  { row: 5, col: 5 },
  { row: 5, col: 6 },
  { row: 5, col: 7 },
];
